all: false
force-file-write: false
formatter: goimports
log-level: info
recursive: false
template: testify
packages:
  mockery/repository:
    config:
      dir: "{{.InterfaceDir}}"
      filename: "repository_mock.go"
      pkgname: "{{.SrcPackageName}}"
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      AnyRepository: